name: Publish Package to npmjs
on:
  push:
    tags: ['*']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Create release
        uses: actions/github-script@v5
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ env.TAG }}",
              generate_release_notes: true
            })
